### ISSUE TITLE
Suggestion: cleaning test/gemfiles/* directories

### ISSUE THREAD

**Issue by junaruga** [cucumber/multi_test#17]
Right now there are some directories for the test cases.

```
$ ls test/gemfiles/ | sort
activesupport-4.0.0/
activesupport-4.1.0/
activesupport-5.0.0/
minitest-5.0.1/
minitest-5.1.0/
minitest-5.2.0/
minitest-5.9.0/
plain-ruby/
rspec-1.3.2/
rspec-2.14/
rspec-3.0/
rspec-3.1/
test-unit-2.4.8/
test-unit-2.4.9/
```

Right now the running time for JRuby is 8 min 55 secs.
I think we the cases are too much. 
https://travis-ci.org/cucumber/multi_test/builds/500408672

I think we can clean and reduce the cases.

Right now each testing gem's latest version is like this.
https://rubygems.org/gems/minitest : the latest version: 5.11.3
https://rubygems.org/gems/test-unit : the latest version: 3.3.0
https://rubygems.org/gems/rspec : the latest version: 3.8.0
https://rubygems.org/gems/activesupport : the latest version: 5.2.2

My suggestion is like this.
I added minitest 4. Because minitest 4's interface is different with minitest 5.
It's worth to test with it.

```
$ ls test/gemfiles/ | sort
activesupport-4/
activesupport-5/
minitest-4/
minitest-5/
plain-ruby/
rspec-1/
rspec-2/
rspec-3/
test-unit-2/
test-unit-3/
```

And maybe we can also run each cases in parallel with threads modifying `test/all`.
That saves the running time for tests.

How do you think?

**Comment by junaruga** [comment]
@olleolleolle how do you think?

**Comment by olleolleolle** [comment]
Reducing the tested matrix: +1!

**Comment by junaruga** [comment]
Okay. thanks.
I want you to merge current 1 PR for rspec-3.8 at first.
@olleolleolle Then do you want to send pull-request for this ticket?
Though I thought I would prepare for that.

**Comment by olleolleolle** [comment]
(I have to leave for the day, so if you beat me to this, I'm OK with that, too.)

**Comment by junaruga** [comment]
@olleolleolle sure I will send the PR today.
