### ISSUE TITLE
Suggestion: do not mange test/gemfiles/*/Gemfile.lock

### ISSUE THREAD

**Issue by junaruga** [cucumber/multi_test#18]
The suggestion is simple.
Shall we stop managing `test/gemfiles/*/Gemfile.lock` on this repository?
That means we will manage the dependency version by only `test/gemfiles/*/Gemfile`.
Because simply managing it by `Gemfile.lock` is hard.

**Comment by junaruga** [comment]
@olleolleolle how about this? How do you think?

**Comment by olleolleolle** [comment]
I think it's fair - and we can ask the Travis CI  configuration to run a weekly cron test - to see if things break.

**Comment by junaruga** [comment]
I agree for "a weekly cron test". But how about "a daily cron test"? It's too much?

**Comment by olleolleolle** [comment]
Daily is cheap, too.

**Comment by junaruga** [comment]
So, I prepare the "daily".

**Comment by olleolleolle** [comment]
I have a PR for this, pushing soon.

**Comment by junaruga** [comment]
Great!

**Comment by olleolleolle** [comment]
This is done in #19. Closing!
